version: '3'

services:
    web:
        build: ./
        ports:
            - "8081:8081"
        volumes:
            - "./src:/code/src"
        container_name: web12

    mongodb:
        image: "mongo"
        container_name: mongodb12
